[font]
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Italic" }
size = 13.0

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 50_000

[window]
opacity = 0.8

[general]
import = [
    "~/.config/alacritty/current_theme.toml"
]

#----------------------------------------------------------------------------


[selection]
save_to_clipboard = true  # Auto-copy selection to clipboard

[mouse]
hide_when_typing = true  # More immersive typing experience

[cursor]
style = "Block"  # Classic Cyberpunk block cursor
unfocused_hollow = true  # Hollow cursor when terminal is unfocused
thickness = 0.2  # Adds some glow effect
